### ISSUE TITLE
server changed name again

### ISSUE THREAD

**Issue by bvdbos** [athombv/nl.buienradar#18]
About 10 months ago the server-name changed to gadgets ( #12 ) but now they changed it back...
https://github.com/athombv/homey/issues/1694
and
https://www.buienradar.nl/overbuienradar/gratis-weerdata

**Comment by mruiter** [comment]
there are a lot of questions comming up on forum and slack why a largely used program like this doest get the simple url change pushed quickly.
People depend on the buienradar for screen and orher controls. 
Please push the changed url fast because people are loosing trust in Homey because the failure on these simple tings

**Comment by BasKiers** [comment]
Hi,

The url is now changed and the update is pushed to the appstore.
Thanks for the issue report.

Regards,
Bas
