### ISSUE TITLE
Works on one homey, not on the other

### ISSUE THREAD

**Issue by edtst** [athombv/nl.buienradar#2]
I installed this app on my first homey as the first app. It works there and pretty well. Allthough sometimes the answers take a while.

On my othe rhomey I installe dit as the last app (like Kaku, somfy etc). It won't respond to any command. I tested by letting homey repeat my commands and it understands them.

**Comment by freekwebdesign** [comment]
This issue is not necessary a problem with the buienradar app.
It could be that Homey 'lost its voice'. This can be fixed by downloading another new voice and enabling this new one.
Besides in Homey 0.8.21 there are some improvements in which this problem should not occur anymore.
If this is not the case, can you provide me with some more details?
