### ISSUE TITLE
Always 0 minutes as result

### ISSUE THREAD

**Issue by jdh009** [athombv/nl.buienradar#8]
What is your Homey version (Settings → System)?

Homey Firmware Version: 0.8.30

What did you try to achieve?

Please include detailed steps how we can reproduce the issue

The only thing i asked and later typed was:

"gaat het regenen in de komende 2 uur", "gaat het regenen in de komende 6 uur", "gaat het regenen in de komende 30 minuten" and "gaat het regenen in de komende 60 minuten"

What was the result?

"ja, er is gemiddelde regen verwacht in 0 minuten" except the 6 hours, then it knows that it is more than 2 hours and says it does not work.

What did you expect as result?

If it was or was not going to rain in the coming x min/hour

**Comment by freekwebdesign** [comment]
Hmm that is strange, I tried out the same sentences on my Homey (0.8.30) which worked fine.
Did you already try to reinstall the app and reboot Homey?

**Comment by jdh009** [comment]
I tried both a reinstall of the app and a reboot before reporting this. I will upload a short video that shows it.

**Comment by freekwebdesign** [comment]
Thanks for making the video, that gives me a clear insight which phrases go wrong.
The Dutch output is a bit rough at the moment because the text-parser is based on the English version of the app. At the moment I am working on building a proper Dutch text-parser for the next version of the app.

The correct way should be that there is no extra sentences after saying that it is not in the correct interval. I will also fix that in Dutch for the new version.

**Comment by freekwebdesign** [comment]
@jdh009 The app is updated to version 1.1.7, which should solve your issues!
